config/routes.rb
Rails.application.routes.draw do
  get 'site/index'

  devise_for :users
  resources :text_memories
  root 'site#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/text_memory.rb
class TextMemory < ApplicationRecord
    belongs_to :user

  # ensure that a user_id is present
  validates :user_id, presence: true

  # ensure that title is present
  validates :title, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :text_memories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :authenticate_user!
  def index
    # retrieve all Text Memories ordered by descending creation timestamp
    @text_memories = current_user.text_memories.order('created_at desc')
  end
end

app/controllers/text_memories_controller.rb
class TextMemoriesController < ApplicationController
  before_action :set_text_memory, only: [:show, :edit, :update, :destroy]  
  before_action :authenticate_user!

  # GET /text_memories
  # GET /text_memories.json
  def index
    @text_memories = TextMemory.all
  end

  # GET /text_memories/1
  # GET /text_memories/1.json
  def show
  end

  # GET /text_memories/new
  def new
    @text_memory = current_user.text_memories.new
  end

  # GET /text_memories/1/edit
  def edit
  end

  # POST /text_memories
  # POST /text_memories.json
  def create
    @text_memory = current_user.text_memories.new(text_memory_params)

    respond_to do |format|
      if @text_memory.save
        format.html { redirect_to @text_memory, notice: 'Text memory was successfully created.' }
        format.json { render :show, status: :created, location: @text_memory }
      else
        format.html { render :new }
        format.json { render json: @text_memory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /text_memories/1
  # PATCH/PUT /text_memories/1.json
  def update
    respond_to do |format|
      if @text_memory.update(text_memory_params)
        format.html { redirect_to @text_memory, notice: 'Text memory was successfully updated.' }
        format.json { render :show, status: :ok, location: @text_memory }
      else
        format.html { render :edit }
        format.json { render json: @text_memory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_memories/1
  # DELETE /text_memories/1.json
  def destroy
    @text_memory.destroy
    respond_to do |format|
      format.html { redirect_to text_memories_url, notice: 'Text memory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text_memory
      unless @text_memory = current_user.text_memories.where(id: params[:id]).first
        flash[:alert] = 'TextMemory not found.'
        redirect_to root_url
      end
      # @text_memory = TextMemory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def text_memory_params
      params.require(:text_memory).permit(:title, :text, :date, :lat, :lon)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/text_memories_helper.rb
module TextMemoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemoryMapper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
</html>

app/views/site/index.html.erb
<h2>Latest Text Memories</h2>
<table style="width: 100%">
  <thead>
    <tr>
      <th><%= link_to "Text Memories", text_memories_path %></th>
    </tr>
  </thead>

  <tbody>
  <% @text_memories.each do |text_memory| %>
    <tr>
      <td><%= link_to text_memory.title, text_memory %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/text_memories/_form.html.erb
<%= form_for(text_memory) do |f| %>
  <% if text_memory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(text_memory.errors.count, "error") %> prohibited this text_memory from being saved:</h2>

      <ul>
      <% text_memory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>

  <div class="field">
    <%= f.label :lat %>
    <%= f.text_field :lat %>
  </div>

  <div class="field">
    <%= f.label :lon %>
    <%= f.text_field :lon %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/text_memories/edit.html.erb
<h1>Editing Text Memory</h1>

<%= render 'form', text_memory: @text_memory %>

<%= link_to 'Show', @text_memory %> |
<%= link_to 'Back', text_memories_path %>

app/views/text_memories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Text Memories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th>Date</th>
      <th>Lat</th>
      <th>Lon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @text_memories.each do |text_memory| %>
      <tr>
        <td><%= text_memory.title %></td>
        <td><%= text_memory.text %></td>
        <td><%= text_memory.date %></td>
        <td><%= text_memory.lat %></td>
        <td><%= text_memory.lon %></td>
        <td><%= link_to 'Show', text_memory %></td>
        <td><%= link_to 'Edit', edit_text_memory_path(text_memory) %></td>
        <td><%= link_to 'Destroy', text_memory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Text Memory', new_text_memory_path %>

app/views/text_memories/new.html.erb
<h1>New Text Memory</h1>

<%= render 'form', text_memory: @text_memory %>

<%= link_to 'Back', text_memories_path %>

app/views/text_memories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @text_memory.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @text_memory.text %>
</p>

<p>
  <strong>Date:</strong>
  <%= @text_memory.date %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @text_memory.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @text_memory.lon %>
</p>

<%= link_to 'Edit', edit_text_memory_path(@text_memory) %> |
<%= link_to 'Back', text_memories_path %>